volumes:
  kestra_db_data:
    driver: local
  kestra_storage:
    driver: local

services:
  #Kestra internal engine database
  kestra_postgres:
    image: postgres:17
    volumes:
      - kestra_db_data:/var/lib/postgresql
    environment:
      POSTGRES_DB: kestra
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 30s
      timeout: 10s
      retries: 10
  
  kestra:
    image: kestra/kestra:v1.1
    pull_policy: always
    user: "root"
    command: server standalone
    volumes:
      - kestra_storage:/app/storage
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/kestra-wd:/tmp/kestra-wd
    
    env_file:
      - .env
    environment:
      
      ENV_GCP_SERVICE_ACCOUNT_B64: ${GCP_SERVICE_ACCOUNT_B64}
      ENV_GCS_BUCKET: ${GCS_BUCKET}
      ENV_GCP_PROJECT_ID: ${GCP_PROJECT_ID}
      ENV_GEMINI_API_KEY: ${GEMINI_API_KEY}
      
      KESTRA_CONFIGURATION: |
        datasources:
          postgres:
            url: jdbc:postgresql://kestra_postgres:5432/kestra
            driverClassName: org.postgresql.Driver
            username: admin
            password: admin
        kestra:
          tutorial-enabled: false
          secret:
            type: TYPESAFE
          server:
            basicAuth:
              username: "admin@wind.com"
              password: Admin1234!
          repository:
            type: postgres
          storage:
            type: local
            local:
              base-path: /app/storage
          queue:
            type: postgres
          ai:
            type: gemini
            gemini:
              model-name: gemini-2.0-flash
              api-key: ${GEMINI_API_KEY}
          tasks:
            tmpDir:
              path: /tmp/kestra-wd-tmp
          url: http://localhost:8080
    ports:
      - "8080:8080"
      - "8081:8081"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    depends_on:
      kestra_postgres:
        condition: service_started